[package]
name = "dfx_key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ring = "0.16.11"
pem = "1.0.2"
simple_asn1 = "0.6.1"
ic-types = "0.3.0"
openssl = "0.10.38"
